### ISSUE TITLE
VNC dying when opening VS Code

### ISSUE THREAD

**Issue by davidoort** [FS-Online/Driverless-Competition-Simulator#14] opened 2020-05-06 07:17 UTC
Steps to replicate:

- Start the VM instance from GCP
- ssh into the instance and restart vncdisplay.service
- On your laptop run
```
ssh -NL 5900:localhost:5900 <user>@<ip>
vncviewer DotWhenNoCursor=1 localhost:5900
```
- Log in through the remote display
- Open VS Code
- Wait for the VNC tunnel to interrupt and close
- Inspecting the logs should show something like the screenshot below.

![image](https://user-images.githubusercontent.com/21220927/81147349-661a4080-8f7a-11ea-989b-c499bedd586d.png)

or (when running `sudo journalctl -ru vncdisplay.service`):
![image](https://user-images.githubusercontent.com/21220927/81148972-97e0d680-8f7d-11ea-9b42-2031e37737a1.png)

**Comment by mvanlobensels** [comment] 2020-05-08 13:09
Same problem. This is highly annoying indeed

**Comment by SijmenHuizenga** [comment] 2020-05-14 18:26
Trying to find the root cause of this problem seems impossible. And even if we would get this to work, visual studio code wouldn't behave as snappy as you are used to on your local computer. Therefore I propose we use [Visual Studio Code Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh): 

> The Remote - SSH extension lets you use any remote machine with a SSH server as your development environment.

So we can open a folder on the remote machine using ssh authorization that is already in place. Save directly to the machine and use vnc to run the software.

Closing this ticket because above seems to be a better workaround.

**Closed by SijmenHuizenga** 2020-05-14 18:26 UTC
Labels: bug
